version: "3"
services:
  bootnode:
    build: "./"
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/devnet.json"
      - "--networkid=17243"
      - "--nodekeyhex=633ab917d09441de38ae9251e79ced41df39a1c338842b826c18fb1773246e18"
      - "--syncmode=full"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--light.serve=50"
      - "--light.maxpeers=2"
    volumes:
      - "./genesis/devnet.json:/datadir/devnet.json"
    ports:
      - "8545:8545"
      - "8546:8546"
    restart: always
  validator:
    build: "./"
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/devnet.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x00a601f45688dba8a070722073b015277cf36725"
      - "--miner.etherbase=0x00a601f45688dba8a070722073b015277cf36725"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=17243"
    volumes:
      - "./genesis/devnet.json:/datadir/devnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
  faucet:
    build:
      context: "./"
      dockerfile: Dockerfile.faucet
    command:
      - "--genesis=/datadir/devnet.json"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--network=17243"
      - "--faucet.name='Chiliz Testnet'"
      - "--faucet.amount=1"
      - "--account.json=/datadir/keystore/UTC--2021-04-15T12-00-01.000Z--00a601f45688dba8a070722073b015277cf36725"
      - "--account.pass=/datadir/password.txt"
      - "--noauth=true"
      - "--faucet.minutes=1"
      - "--faucet.fixedprice=7000000000"
      - "--bep2eContracts=0x931497160a90cE18c361b49F007d7285951A1A3e,0x4BadFd82f7eF1772E848A2482B570F95FE4cBff9,0xb4b27b9e52dC421FF82b74f9d36bAa39b1181Dc2,0xd9CbFcd6Ed02032a2591C5a7c0dFB34e9d7F7F2D,0x48E32f760fA1dabCd585C20d235fa6Dbef324d80,0x8377C51D89a3F143464AD0280CAcFEd82691d5B1,0x094DeedE5D44C549D9a28AE946761e36513C5f72,0xE8DcBf10217eB753729c2e30A5F641b5f582bBbf,0xEeE279AD3C283BC34A5Be567bb889Ce2617f2288,0x4eAD97E7D8A477fE5df88B4CD5025E255c42Ff26,0x16Ca3C932F497Eb2BED8820249698B9d6006Eb41,0x8c6Ba7dd73436ba35FC645CCb7a80B2d71F48A85"
      - "--bep2eSymbols=testSSU,testGAL,testCITY,testPSG,testBAR,testJUV,testMENGO,testTRA,testACM,testATM,testAFC,testINTER"
      - "--bep2eNames=Socios United,Galatasaray S.K.,Manchester City FC,Paris Saint-Germai,FC Barcelona,Juventus,Flamengo,Trabzonspor,AC Milan,Atlético de Madrid,Arsenal FC,Inter Milan"
      - "--bep2eAmounts=1,1,1,1,1,1,1,1,1,1,1,1"
    volumes:
      - "./genesis/devnet.json:/datadir/devnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
    ports:
      - "8087:8080"